apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  serviceAccountName: curlpod-serviceaccount
  containers:
  - name: curl-container
    image: curlimages/curl:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]