apiVersion: v1
kind: Pod
metadata:
  name: dummy
spec:
  containers:
  - name: dummy-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do ping -c 4 google.com; sleep 600; done"]